
var quote = new Array()
quote[0] = "It is better to have loved and lost than just to have lost."
quote[1] = "It is bad luck to be superstitious."
quote[2] = "If it jams, force it. If it breaks, it needed replacing anyway."
quote[3] = "Always remember that you are unique. Just like everyone else."
quote[4] = "A woman without a man is like a fish without a bicycle."
quote[5] = "A bachelor is a guy who is footloose and fiancee free."
quote[6] = "If Yoda a great Jedi master he is, why not a good sentence construct can he?"
quote[7] = "People will remember you better if you always wear the same outfit."
quote[8] = "He's dead, Jim You take his tri-corder and I'll search his pockets."
quote[9] = "All things are possible except for skiing through a revolving door."
quote[10] = "Only two of my personalities are schizophrenic, but one of them is paranoid and the other one is out to get him."
quote[11] = "If you love a thing of beauty, set it free. If it doesn't come back to you, hunt it down and kill it."
quote[12] = "I may be schizophrenic, but at least I'll always have each other."
quote[13] = "Give your child mental blocks for Christmas."
quote[14] = "I stayed up all night playing poker with tarot cards. I got a full house and four people died."
quote[15] = "It is impossible to make anything foolproof but you can stop a determined idiot."
quote[16] = "Parker's Law: Beauty is only skin deep, but ugly goes clean to the bone."
quote[17] = "Those who can't write, write manuals."
quote[18] = "All generalities are false."
quote[19] = "I'd give my right arm to be ambidextrous."
quote[20] = "Duct tape is like the Force.  It has a light side, and a dark side, and it holds the universe together."
quote[21] = "I used to think I was indecisive, but now I'm not so sure."
quote[22] = "Boob's Law: You always find something in the last place you look."
quote[23] = "Cole's Law:  Thinly sliced cabbage."
quote[24] = "Things are more like they used to be than they are now."
quote[25] = "There is so much sand in Northern Africa that if it were spread out it would completely cover the Sahara Desert."
quote[26] = "It has been said that we only use 15% of our brain.  I wonder what we do with the other 75%?"
quote[27] = "If you want your spouse to listen and pay strict attention to every word you say, talk in your sleep."
quote[28] = "If you have a difficult task, give it to someone lazy ... that person will find an easier way to do it."
quote[29] = "The way to make a small fortune in the commodities market is to start with a large fortune."
quote[30] = "Automatic simply means that you cannot repair it yourself."
quote[31] = "A clean desk is a sign of a sick mind."
quote[32] = "A closed mouth says nothing wrong; a closed mind does nothing right."
quote[33] = "A complex system that works is invariably found to have evolved from a simple system that worked."
quote[34] = "A computer makes as many mistakes in one second as three men working for thirty years straight."
quote[35] = "A conference is simply an admission that you want somebody else to join you in your troubles."
quote[36] = "A dog is a dog except when he is facing you. Then he is Mr. Dog."
quote[37] = "A fellow who is always declaring that he is no fool usually harbors suspicions to the contrary."
quote[38] = "A fool and his money are some party."
quote[39] = "A friend in power is a friend lost."
quote[40] = "A good listener not only is popular everywhere but also, after a while, knows something."
quote[41] = "A great deal of money is never enough once you have it."
quote[42] = "A hunch is creativity trying to tell you something."
quote[43] = "A major failure will not occur until after the unit has passed final inspection."
quote[44] = "A man does not look behind the door unless he has stood there himself."
quote[45] = "A man will believe anything that does not cost him anything."
quote[46] = "A meeting is an event at which the minutes are kept and the hours are lost."
quote[47] = "A miser is a fellow who lives within his income. He is also called a magician."
quote[48] = "A misplaced decimal point will always end up where it will do the greatest damage."
quote[49] = "A narrow mind has a broad tongue."
quote[50] = "A seeming ignorance is often a most necessary part of worldly knowledge.     "
quote[51] = "A short cut is the longest distance between two points."
quote[52] = "A synonym is a word you use when you can't spell the other one."
quote[53] = "A yacht is a hole in the water, lined with wood, steel, or fiberglass, through which one pours all his money."
quote[54] = "Academic rivalries are so intense because the stakes are so small."
quote[55] = "Activity is the politician's substitute for achievement."
quote[56] = "After all is said and done, a hell of a lot more is said than done."
quote[57] = "All great discoveries are made by mistake."
quote[58] = "All warranties expire upon payment of invoice."
quote[59] = "All's well that ends."
quote[60] = "Almost everything in life is easier to get into than out of."
quote[61] = "Although I may disagree with what you say, I will defend to the death your right to hear me tell you how wrong you are."
quote[62] = "Always forgive your enemies - nothing else annoys them as much."
quote[63] = "Ambition is the curse of the political class."
quote[64] = "Among economists, the real world is generally considered to be a special case."
quote[65] = "An easily understood, workable falsehood is more useful than a complex, incomprehensible truth."
quote[66] = "An efficient bureaucracy is the greatest threat to liberty."
quote[67] = "An elephant is a mouse built to government specifications."
quote[68] = "An expert is one who knows more and more about less and less until he knows absolutely everything about nothing."
quote[69] = "An infinite number of mediocrities do not add up to one genius."
quote[70] = "An open mouth oft-times accompanies a closed mind."
quote[71] = "Anger is never without an argument, or with a good one."
quote[72] = "Any appetite is its own excuse for existing."
quote[73] = "Any contract drawn in more than 50 words contains at least one loophole."
quote[74] = "Any given computer program, when running, is obsolete."
quote[75] = "Any machine design must contain at least one part which is obsolete, two parts which are unobtainable, and three parts which are still under development."
quote[76] = "Any simple theory will be worded in the most complicated terms."
quote[77] = "Any sufficiently advanced technology is indistinguishable from magic."
quote[78] = "Anyone can handle a crisis. It's everyday living that kills you."
quote[79] = "Anyone in good enough condition to run three miles a day is in good enough condition not to have to."
quote[80] = "Art is a passion pursued with discipline; science is a discipline pursued with passion."
quote[81] = "As the rabbit said, if that ain't a wolf, it's a hell of a big dog."

var randomquote = Math.floor(Math.random()*(quote.length));
function printquote(){
document.write(quote[randomquote].fontcolor("grey").italics());
}




